name: Build with xelatex
on:
  push:
    paths:
      - 'test.tex'
      - 'characters/**'
      - 'template/**'
      - 'character-sheet-settings.tex'
  pull_request:
    paths:
      - 'characters/**'
      - 'template/**'
      - 'character-sheet-settings.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile character tex files
        uses: mortebrume/DND-5e-LaTeX-Action@main
        with:
          root_file: 'test.tex'
          compiler: xelatex
          runs: 2
          args: "--file-line-error --interaction=nonstopmode"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: test.pdf
